config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'
  resources :clients do
    resources :client_details
  end
  resources :events
  get 'home/index'
end

app/models/client_detail.rb
class ClientDetail < ApplicationRecord
  belongs_to :client
  belongs_to :user

  validates :title, presence: true
end

app/controllers/client_details_controller.rb
class ClientDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_client, only: [:index]

  def index
    if @client
      @client_details = @client.client_details
      @client_detail = ClientDetail.new
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @client = Client.find(params[:client_id])
    @client_detail = ClientDetail.new
  end

  def create
    @client = Client.find(params[:client_id])
  
    if @client.user == current_user
      @client_detail = @client.client_details.build(client_detail_params)
      @client_detail.user = current_user
  
      if @client_detail.save
        redirect_to client_client_details_path(@client)
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    @client = Client.find(params[:client_id])
  
    if @client.user == current_user
      @client_detail = @client.client_details.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @client = Client.find(params[:client_id])
    @client_detail = @client.client_details.find(params[:id])

    if @client_detail.update(client_detail_params)
      redirect_to client_client_details_path(@client)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @client = Client.find(params[:client_id])
    @client_detail = @client.client_details.find(params[:id])
    @client_detail.destroy
    redirect_to client_client_details_path(@client)
  end

  private

  def client_detail_params
    params.require(:client_detail).permit(:title, :content)
  end

  def find_client
    @client = Client.find_by(id: params[:client_id], user_id: current_user.id)
  end
end

app/helpers/client_details_helper.rb
module ClientDetailsHelper
end

app/views/client_details/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>追加情報編集ページ</title>
  <%= stylesheet_link_tag "client_details" %>
</head>
<body>
  <h1><%= "#{@client.client_lastname}様の追加情報を編集する" %></h1>

  <%= form_with model: @client_detail, url: client_client_detail_path(@client, @client_detail), method: :patch do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div>
      <label for="title">タイトル:</label>
      <%= f.text_field :title, id: "title" %>
    </div>

    <div>
      <label for="content">内容:</label>
      <%= f.text_area :content, id: "content" %>
    </div>

    <div>
      <%= f.submit "更新する" %>
    </div>
  <% end %>

  <div class="top-right">
    <%= link_to '戻る', client_client_details_path(@client) %>
  </div>
</body>
</html>

app/views/client_details/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client Details</title>
  <%= stylesheet_link_tag "client_details" %>
</head>
<body>
  <h1><%= "#{@client.client_lastname}様の顧客情報" %></h1>

  <h2>追加情報一覧</h2>

  <div id="field-container">
    <% @client_details.each do |detail| %>
      <div>
        <div class="title">
          <%= detail.title %>
        </div>
        <div class="content">
          <%= detail.content %>
        </div>
        <div>
          <%= link_to '編集', edit_client_client_detail_path(@client, detail) %>
          <%= link_to '削除', client_client_detail_path(@client, detail), method: :delete, data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="top-right">
    <p><%= link_to '追加情報を登録する', new_client_client_detail_path(@client) %></p>
    <p><%= link_to '戻る', client_path(@client) %></p>
  </div>
</body>
</html>

app/views/client_details/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>追加情報登録ページ</title>
  <%= stylesheet_link_tag "client_details" %>
</head>
<body>
  <h1><%= "#{@client.client_lastname}様の追加情報を登録する" %></h1>

  <%= form_with model: @client_detail, url: client_client_details_path(@client) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div>
      <label for="title">タイトル</label>
      <%= f.text_field :title, id: "title" %>
    </div>

    <div>
      <label for="content">内容</label>
      <%= f.text_area :content, id: "content" %>
    </div>

    <div class="form-submit">
      <%= f.submit "登録する" %>
    </div>
  <% end %>
   
  <div class="top-right">
    <%= link_to '戻る', client_client_details_path(@client) %>
  </div>
</body>
</html>