config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'
  resources :clients do
    resources :client_details
  end
  resources :events
  get 'home/index'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_details
  belongs_to :user

  validates :client_firstname, presence: true
  validates :client_firstname, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角（漢字・ひらがな・カタカナ）で入力してください' }
  validates :client_lastname, presence: true
  validates :client_lastname, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角（漢字・ひらがな・カタカナ）で入力してください' }
  validates :client_firstname_kana, presence: true
  validates :client_firstname_kana, format: { with: /\A[ァ-ヶー]+\z/, message: 'は全角（カタカナ）で入力してください' }
  validates :client_lastname_kana, presence: true
  validates :client_lastname_kana, format: { with: /\A[ァ-ヶー]+\z/, message: 'は全角（カタカナ）で入力してください' }
  validates :birthday, presence: true
  validates :gender_id, presence: true, exclusion: { in: [1] }
  validates :post_code, presence: true
  validates :post_code,format: { with: /\A\d{3}-\d{4}\z/, message: 'must be in the format of 3 digits, hyphen, and 4 digits' }
  validates :prefecture_id, presence: true, exclusion: { in: [1] }
  validates :municipality, presence: true
  validates :address, presence: true
  validates :phone_number,format: { with: /\A[0-9]{10,11}\z/, message: 'must be 10 to 11 digits and contain only numbers' }
  validates :mobile_number,format: { with: /\A[0-9]{10,11}\z/, message: 'must be 10 to 11 digits and contain only numbers' }
  # validates :building_name
  # validates :phone_number
  # validates :mobile_number
  # validates :company_name
  # validates :project
  # validates :note



  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :gender
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @clients = current_user.clients
    @clients = sort_by_name(@clients)
  end

  def new
    @client = Client.new
  end

  def create
    @client = current_user.clients.build(client_params)

    if @client.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @client = Client.find(params[:id])
    if @client.user != current_user
      redirect_to clients_path
    end
  end

  def edit
    @client = Client.find(params[:id])
    if @client.user != current_user
      redirect_to clients_path
    end
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    client.client_details.destroy_all
    redirect_to clients_path
  end

  def sort_by_name(clients = [])
    origin = "ａ-ｚＡ-Ｚァ-ン０-９ぁぃぅぇぉがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゃゅょっゎァィゥェォガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポャュョッヮ"
    normalize = "a-zA-Zぁ-ん0-9あいうえおかきくけこさしすせそたちつてとはひふへほはひふへほやゆよつわあいうえおかきくけこさしすせそたちつてとはひふへほはひふへほやゆよつわ"

    clients.sort_by do |client|
      [client.client_lastname_kana.tr(origin, normalize), client.client_firstname_kana.tr(origin, normalize)]
    end
  end

  
  private
  def client_params
    params.require(:client).permit(:client_firstname, :client_lastname, :client_firstname_kana, :client_lastname_kana, :birthday, :gender_id, :post_code, :prefecture_id, :municipality, :address, :building_name, :phone_number, :mobile_number, :company_name, :project, :note)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Client</title>
  <%= stylesheet_link_tag "clients" %>
</head>
<body>
  <h1>顧客情報編集</h1>
  <%= form_with(model: @client) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <div class="name-fields">
        <%= f.label :client_lastname, '姓' %>
        <%= f.text_field :client_lastname %>
      </div>
      <div class="name-fields">
        <%= f.label :client_firstname, '名' %>
        <%= f.text_field :client_firstname %>
      </div>
    </div>
    <div class="form-group">
      <div class="name-fields">
        <%= f.label :client_lastname_kana, 'セイ' %>
        <%= f.text_field :client_lastname_kana %>
      </div>
      <div class="name-fields">
        <%= f.label :client_firstname_kana, 'メイ' %>
        <%= f.text_field :client_firstname_kana %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :birthday, '生年月日' %>
      <%= f.text_field :birthday, type: "date" %>
    </div>
    <div class="form-group">
      <%= f.label :gender_id, '性別' %>
      <%= f.select :gender_id, options_for_select(Gender.all.map { |gender| [gender.name, gender.id] }, @client.gender_id) %>
    </div>
    <div class="form-group">
      <%= f.label :post_code, '郵便番号' %>
      <%= f.text_field :post_code %>
    </div>
    <div class="form-group">
      <%= f.label :prefecture_id, '都道府県' %>
      <%= f.select :prefecture_id, options_for_select(Prefecture.all.map { |prefecture| [prefecture.name, prefecture.id] }, @client.prefecture_id) %>
    </div>
    <div class="form-group">
      <%= f.label :municipality, '市区町村' %>
      <%= f.text_field :municipality, class: "long-input" %>
    </div>
    <div class="form-group">
      <%= f.label :address, '番地' %>
      <%= f.text_field :address, class: "long-input" %>
    </div>
    <div class="form-group">
      <%= f.label :building_name, '建物名' %>
      <%= f.text_field :building_name, class: "long-input" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number, 'ご自宅番号' %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="form-group">
      <%= f.label :mobile_number, '携帯番号' %>
      <%= f.text_field :mobile_number %>
    </div>
    <div class="form-group">
      <%= f.label :company_name, '会社名' %>
      <%= f.text_field :company_name, class: "long-input" %>
    </div>
    <div class="form-group">
      <%= f.label :project, '案件' %>
      <%= f.text_area :project %>
    </div>
    <div class="form-group">
      <%= f.label :note, '備考' %>
      <%= f.text_area :note %>
    </div>
    <div class="form-group">
      <%= f.submit "更新" %>
    </div>
    <div class="top-right">
      <%= link_to "戻る", client_path(@client) %>
    </div>
  <% end %>
</body>
</html>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client List</title>
  <%= stylesheet_link_tag "clients" %>
</head>
<body>
  <h1>顧客一覧</h1>

  <div>
    <% current_row = nil %>
    <% @clients.each do |client| %>
      <% if current_row != client.client_lastname_kana[0] %>
        <% current_row = client.client_lastname_kana[0] %>
        <h2><%= current_row %></h2>
      <% end %>
      <div>
        <%= link_to "#{client.client_lastname} #{client.client_firstname}", client_path(client.id) %>
      </div>
    <% end %>
  </div>
  
  <div class="top-right">
    <p><%= link_to "顧客を追加する", new_client_path %></p>
    <p><%= link_to "戻る", home_index_path %></p>
  </div>
</body>
</html>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Client</title>
  <%= stylesheet_link_tag "clients" %>
</head>
<body>
  <h1>顧客登録</h1>
  <%= form_with(model: @client) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <div class="name-fields">
        <%= f.label :client_lastname, '姓' %>
        <%= f.text_field :client_lastname, placeholder: "例: 山田" %>
      </div>
      <div class="name-fields">
        <%= f.label :client_firstname, '名' %>
        <%= f.text_field :client_firstname, placeholder: "例: 太郎" %>
      </div>
    </div>
    <div class="form-group">
      <div class="name-fields">
        <%= f.label :client_lastname_kana, 'セイ' %>
        <%= f.text_field :client_lastname_kana, placeholder: "例: ヤマダ" %>
      </div>
      <div class="name-fields">
        <%= f.label :client_firstname_kana, 'メイ' %>
        <%= f.text_field :client_firstname_kana, placeholder: "例: タロウ" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :birthday, '生年月日' %>
      <%= f.text_field :birthday, type: "date" %>
    </div>
    <div class="form-group">
      <%= f.label :gender_id, '性別' %>
      <%= f.select :gender_id, options_for_select(Gender.all.map { |gender| [gender.name, gender.id] }, @client.gender_id) %>
    </div>
    <div class="form-group">
      <%= f.label :post_code, '郵便番号' %>
      <%= f.text_field :post_code, placeholder: "例: 123-4567" %>
    </div>
    <div class="form-group">
      <%= f.label :prefecture_id, '都道府県' %>
      <%= f.select :prefecture_id, options_for_select(Prefecture.all.map { |prefecture| [prefecture.name, prefecture.id] }, @client.prefecture_id) %>
    </div>
    <div class="form-group">
      <%= f.label :municipality, '市区町村' %>
      <%= f.text_field :municipality, class: "long-input" %>
    </div>
    <div class="form-group">
      <%= f.label :address, '番地' %>
      <%= f.text_field :address, class: "long-input", placeholder: "例: 1-2-3" %>
    </div>
    <div class="form-group">
      <%= f.label :building_name, '建物名' %>
      <%= f.text_field :building_name, class: "long-input", placeholder: "例: 〇〇ビル5階" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number, 'ご自宅番号' %>
      <%= f.text_field :phone_number, placeholder: "例: 0451112222" %>
    </div>
    <div class="form-group">
      <%= f.label :mobile_number, '携帯番号' %>
      <%= f.text_field :mobile_number, placeholder: "例: 0901112222" %>
    </div>
    <div class="form-group">
      <%= f.label :company_name, '会社名' %>
      <%= f.text_field :company_name, class: "long-input", placeholder: "例: 株式会社〇〇" %>
    </div>
    <div class="form-group">
      <%= f.label :project, '案件' %>
      <%= f.text_area :project %>
    </div>
    <div class="form-group">
      <%= f.label :note, '備考' %>
      <%= f.text_area :note %>
    </div>
    <div class="form-group">
      <%= f.submit "登録" %>
    </div>
    <div class="top-right">
      <%= link_to "戻る", clients_path %>
    </div>
  <% end %>
</body>
</html>

app/views/clients/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client Details</title>
  <%= stylesheet_link_tag "clients" %>
</head>
<body>
  <h1><%= "#{@client.client_lastname}様の顧客情報" %></h1>

  <h2>基本情報</h2>
  <p>氏名: <%= "#{@client.client_lastname} #{@client.client_firstname}" %></p>
  <p>フリガナ: <%= "#{@client.client_lastname_kana} #{@client.client_firstname_kana}" %></p>
  <p>生年月日: <%= @client.birthday %></p>
  <p>性別: <%= @client.gender.name %></p>
  <p>郵便番号: <%= @client.post_code %></p>
  <p>都道府県: <%= @client.prefecture.name %></p>
  <p>市区町村: <%= @client.municipality %></p>
  <p>番地: <%= @client.address %></p>
  <p>建物名: <%= @client.building_name %></p>
  <p>ご自宅番号: <%= @client.phone_number %></p>
  <p>携帯番号: <%= @client.mobile_number %></p>
  <p>会社名: <%= @client.company_name %></p>
  <p>案件: <%= @client.project %></p>
  <p>備考: <%= @client.note %></p>

  <div class="button-container">
    <p><%= link_to "追加情報はこちら", client_client_details_path(@client) %></p>
    <p><%= link_to "編集する", edit_client_path(@client) %></p>
    <p><%= link_to "削除する", client_path(@client), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } %></p>
    <p><%= link_to "戻る", clients_path %></p>
  </div>
</body>
</html>