config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'
  resources :clients do
    resources :client_details
  end
  resources :events
  get 'home/index'
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @event = Event.new
  end

  def new
    @event = Event.new
    @selected_date = params[:date]
  end
  
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path, notice: "予定が追加されました。"
    else
      render :new
    end
  end
  
  private
  
  def event_params
    params.require(:event).permit(:content, :start_time, :end_time)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<%= stylesheet_link_tag "event" %>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <%= month_calendar events: @events, date: @selected_date do |date, events| %>
        <div class="p-2 bg-light mb-2">
          <strong><%= date.day %></strong>
        </div>
        <% events.each do |event| %>
          <div class="p-1 bg-success text-white mb-1 rounded">
            <div class="event-content"><%= event.content %></div>
            <% if event.start_time.present? && event.end_time.present? %>
              <div class="event-time">
                <%= "#{event.start_time.strftime('%H:%M')} 〜 #{event.end_time.strftime('%H:%M')}" %>
              </div>
            <% elsif event.start_time.present? %>
              <div class="event-time">
                <%= event.start_time.strftime("%H:%M") %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6">
      <%= form_with(model: @event, url: events_path, local: true) do |form| %>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
            <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :start_time %>
          <%= form.datetime_select :start_time, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :end_time %>
          <%= form.datetime_select :end_time, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_field :content, class: "form-control" %>
        </div>

        <div class="text-center">
        <%= form.submit "予定を追加", class: "btn btn-primary" %>
    </div>
    <div class="top-right">
      <p><%= link_to "戻る", home_index_path %></p>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_with(model: @event, local: true) do |form| %>
        <%= form.hidden_field :start_time, value: @selected_date %>

        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_field :content, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= form.submit "予定を追加", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>